import React, { useState, useEffect } from 'react';
import '../../styles/carrier/AddLoads.css';
import { API_URL } from '../../config';
import { auth } from '../../firebase';
import Geocoder from '../common/Geocoder';
import RouteMap from '../common/RouteMap';

export default function AddLoads({ onClose, draftLoad, isShipper = false }) {
  const [step, setStep] = useState(1);
  const [chargeName, setChargeName] = useState('');
  const [chargeAmount, setChargeAmount] = useState('');
  const [advancedCharges, setAdvancedCharges] = useState([]); // [{"name": "Detention", "amount": 150}]
  const [loadId, setLoadId] = useState(null); // Will be generated by backend
  const [estimatedDistance, setEstimatedDistance] = useState(null);
  const [estimatedTransitTime, setEstimatedTransitTime] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [matchedCarriers, setMatchedCarriers] = useState([]);
  
  // Additional routes state
  const [additionalRoutes, setAdditionalRoutes] = useState([]); // [{location, type, date}]
  const [showAddRoute, setShowAddRoute] = useState(false);
  const [newRouteLocation, setNewRouteLocation] = useState('');
  const [newRouteType, setNewRouteType] = useState('pickup');
  const [newRouteDate, setNewRouteDate] = useState('');
  
  const [formData, setFormData] = useState({
    // Step 1: Route & Equipment
    origin: '',
    destination: '',
    pickupDate: '',
    deliveryDate: '',
    pickupAppointmentType: 'FCFS', // FCFS or BY_APPOINTMENT
    deliveryAppointmentType: 'FCFS',
    equipmentType: 'Dry Van', // Backend enum format
    loadType: 'FTL', // FTL, LTL, PARTIAL
    weight: '',
    palletCount: '',
    
    // Step 2: Price & Details
    rateType: 'flatRate', // flatRate, perMile, hourly
    linehaul: '',
    fuelSurcharge: '',
    commodity: '',
    specialRequirements: [], // Array of strings
    paymentTerms: 'Quick Pay', // Quick Pay, 15 Days, 30 Days, Custom
    notes: '',
    
    // Step 3: Visibility & Preferences
    visibility: 'public', // public, network, private
    selectedCarriers: [], // For PRIVATE visibility
    autoMatch: true,
    instantBooking: false, // Allow carriers to book without approval
    autoPostToFreightpower: true,
    autoPostToTruckstop: false,
    autoPostTo123loadboard: false,
    notifyOnCarrierViews: true,
    notifyOnOfferReceived: true,
    notifyOnLoadCovered: true,
  });

  // Pre-populate form if resuming a draft load
  useEffect(() => {
    if (draftLoad) {
      setLoadId(draftLoad.load_id);
      
      // Set estimated values from draft
      if (draftLoad.estimated_distance) {
        setEstimatedDistance(draftLoad.estimated_distance);
      }
      if (draftLoad.estimated_transit_time) {
        setEstimatedTransitTime(draftLoad.estimated_transit_time);
      }
      
      // Set additional routes if present
      if (draftLoad.additional_routes && Array.isArray(draftLoad.additional_routes)) {
        setAdditionalRoutes(draftLoad.additional_routes);
      }
      
      setFormData({
        // Step 1
        origin: draftLoad.origin || '',
        destination: draftLoad.destination || '',
        pickupDate: draftLoad.pickup_date || '',
        deliveryDate: draftLoad.delivery_date || '',
        pickupAppointmentType: draftLoad.pickup_appointment_type || 'FCFS',
        deliveryAppointmentType: draftLoad.delivery_appointment_type || 'FCFS',
        equipmentType: draftLoad.equipment_type || 'Dry Van',
        loadType: draftLoad.load_type || 'FTL',
        weight: draftLoad.weight || '',
        palletCount: draftLoad.pallet_count || '',
        
        // Step 2
        rateType: draftLoad.rate_type === 'Flat Rate' ? 'flatRate' : draftLoad.rate_type === 'Per Mile' ? 'perMile' : 'hourly',
        linehaul: draftLoad.linehaul_rate || '',
        fuelSurcharge: draftLoad.fuel_surcharge || '',
        commodity: draftLoad.commodity || '',
        specialRequirements: draftLoad.special_requirements || [],
        paymentTerms: draftLoad.payment_terms || 'Quick Pay',
        notes: draftLoad.notes || '',
        
        // Step 3
        visibility: draftLoad.visibility?.toLowerCase() || 'public',
        selectedCarriers: draftLoad.selected_carriers || [],
        autoMatch: draftLoad.auto_match_ai !== undefined ? draftLoad.auto_match_ai : true,
        instantBooking: draftLoad.instant_booking || false,
        autoPostToFreightpower: draftLoad.auto_post_to_freightpower !== undefined ? draftLoad.auto_post_to_freightpower : true,
        autoPostToTruckstop: draftLoad.auto_post_to_truckstop || false,
        autoPostTo123loadboard: draftLoad.auto_post_to_123loadboard || false,
        notifyOnCarrierViews: draftLoad.notify_on_carrier_views !== undefined ? draftLoad.notify_on_carrier_views : true,
        notifyOnOfferReceived: draftLoad.notify_on_offer_received !== undefined ? draftLoad.notify_on_offer_received : true,
        notifyOnLoadCovered: draftLoad.notify_on_load_covered !== undefined ? draftLoad.notify_on_load_covered : true,
      });
      
      // Set advanced charges if present
      if (draftLoad.advanced_charges && Array.isArray(draftLoad.advanced_charges)) {
        setAdvancedCharges(draftLoad.advanced_charges);
      }
      
      // Determine which step to start at based on what's complete
      if (draftLoad.linehaul_rate) {
        setStep(3); // Has pricing, go to Step 3
      } else if (draftLoad.origin && draftLoad.destination) {
        setStep(2); // Has route, go to Step 2
      }
    }
  }, [draftLoad]);

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleLoadTypeSelect = (type) => {
    setFormData(prev => ({ ...prev, loadType: type }));
  };

  const handleVisibilitySelect = (option) => {
    setFormData(prev => ({ ...prev, visibility: option }));
  };

  const toggleRequirement = (req) => {
    setFormData(prev => ({
      ...prev,
      specialRequirements: prev.specialRequirements.includes(req)
        ? prev.specialRequirements.filter(r => r !== req)
        : [...prev.specialRequirements, req]
    }));
  };

  const handleAddCharge = () => {
    if (chargeName && chargeAmount) {
      setAdvancedCharges(prev => [...prev, { name: chargeName, amount: parseFloat(chargeAmount) }]);
      setChargeName('');
      setChargeAmount('');
    }
  };

  const handleRemoveCharge = (index) => {
    setAdvancedCharges(prev => prev.filter((_, i) => i !== index));
  };

  // Additional routes handlers
  const handleAddRoute = () => {
    if (newRouteLocation && newRouteDate) {
      setAdditionalRoutes(prev => [
        ...prev,
        {
          location: newRouteLocation,
          type: newRouteType,
          date: newRouteDate
        }
      ]);
      // Reset form
      setNewRouteLocation('');
      setNewRouteType('pickup');
      setNewRouteDate('');
      setShowAddRoute(false);
    }
  };

  const handleRemoveRoute = (index) => {
    setAdditionalRoutes(prev => prev.filter((_, i) => i !== index));
  };

  // Trigger AI distance calculation when origin and destination are filled
  useEffect(() => {
    const calculateDistance = async () => {
      if (formData.origin && formData.destination && !loadId) {
        try {
          const token = await getAuthToken();
          const response = await fetch(`${API_URL}/ai/calculate-distance`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify({
              origin: formData.origin,
              destination: formData.destination
            })
          });
          
          if (response.ok) {
            const data = await response.json();
            setEstimatedDistance(data.distance_miles);
            setEstimatedTransitTime(data.estimated_hours);
            console.log('✅ Distance calculated:', data);
          }
        } catch (err) {
          console.log('Distance calculation failed:', err);
        }
      }
    };

    // Debounce the calculation
    const timer = setTimeout(calculateDistance, 1000);
    return () => clearTimeout(timer);
  }, [formData.origin, formData.destination]);

  // Auto-calculate load cost when rate per mile and distance are available
  useEffect(() => {
    if (formData.rateType === 'perMile' && estimatedDistance && formData.linehaul) {
      const ratePerMile = parseFloat(formData.linehaul);
      if (!isNaN(ratePerMile)) {
        const calculatedLinehaul = estimatedDistance * ratePerMile;
        console.log(`💰 Calculated linehaul: ${calculatedLinehaul.toFixed(2)} (${estimatedDistance} miles × $${ratePerMile}/mile)`);
      }
    }
  }, [formData.rateType, formData.linehaul, estimatedDistance]);

  const calculateTotalPay = () => {
    let linehaul = parseFloat(formData.linehaul) || 0;
    // If per-mile pricing, multiply by distance
    if (formData.rateType === 'perMile' && estimatedDistance) {
      linehaul = linehaul * estimatedDistance;
    }
    const fuelSurcharge = parseFloat(formData.fuelSurcharge) || 0;
    const advancedTotal = advancedCharges.reduce((sum, charge) => sum + parseFloat(charge.amount || 0), 0);
    return linehaul + fuelSurcharge + advancedTotal;
  };

  // Get authentication token
  const getAuthToken = async () => {
    const user = auth.currentUser;
    if (!user) throw new Error('Not authenticated');
    return await user.getIdToken();
  };

  // Step 1: Create load with route & equipment
  const handleStep1Submit = async () => {
    setIsLoading(true);
    setError(null);
    
    try {
      const token = await getAuthToken();
      
      // Map frontend equipment names to backend enum values
      const equipmentTypeMap = {
        'Dry Van': 'Dry Van',
        'Reefer': 'Reefer',
        'Flatbed': 'Flatbed',
        'Stepdeck': 'Stepdeck',
        'Power Only': 'Power Only'
      };
      
      // Map frontend load types to backend enum values
      const loadTypeMap = {
        'FTL': 'Full Truckload',
        'LTL': 'LTL',
        'Multi-Stop': 'Multi-Stop'
      };
      
      const response = await fetch(`${API_URL}/loads/step1`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          origin: formData.origin,
          destination: formData.destination,
          pickup_date: formData.pickupDate,
          delivery_date: formData.deliveryDate || null,
          pickup_appointment_type: formData.pickupAppointmentType,
          delivery_appointment_type: formData.deliveryAppointmentType,
          equipment_type: equipmentTypeMap[formData.equipmentType] || 'Dry Van',
          load_type: loadTypeMap[formData.loadType] || 'Full Truckload',
          weight: parseFloat(formData.weight),
          pallet_count: formData.palletCount ? parseInt(formData.palletCount) : null,
          additional_routes: additionalRoutes  // Include additional routes
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        // Better error display for validation errors
        const errorMsg = errorData.detail 
          ? (Array.isArray(errorData.detail) 
              ? errorData.detail.map(e => `${e.loc?.join('.')}: ${e.msg}`).join(', ')
              : errorData.detail)
          : 'Failed to create load';
        throw new Error(errorMsg);
      }

      const data = await response.json();
      setLoadId(data.load_id);
      setEstimatedDistance(data.estimated_distance);
      setEstimatedTransitTime(data.estimated_transit_time);
      setStep(2); // Move to step 2
    } catch (err) {
      setError(err.message);
      console.error('Step 1 error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Step 2: Update load with pricing & details
  const handleStep2Submit = async () => {
    if (!loadId) {
      setError('Load ID not found. Please restart.');
      return;
    }
    
    setIsLoading(true);
    setError(null);
    
    try {
      const token = await getAuthToken();
      
      const rateTypeMap = {
        'flatRate': 'Flat Rate',
        'perMile': 'Per Mile',
        'hourly': 'Hourly'
      };
      
      // Calculate actual linehaul based on rate type
      let actualLinehaul = parseFloat(formData.linehaul);
      if (formData.rateType === 'perMile' && estimatedDistance) {
        actualLinehaul = estimatedDistance * parseFloat(formData.linehaul);
      }
      
      const response = await fetch(`${API_URL}/loads/${loadId}/step2`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          rate_type: rateTypeMap[formData.rateType] || 'Flat Rate',
          linehaul_rate: actualLinehaul,
          fuel_surcharge: formData.fuelSurcharge ? parseFloat(formData.fuelSurcharge) : null,
          advanced_charges: advancedCharges,
          commodity: formData.commodity || null,
          special_requirements: formData.specialRequirements,
          payment_terms: formData.paymentTerms,
          notes: formData.notes || null
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        const errorMsg = errorData.detail 
          ? (Array.isArray(errorData.detail) 
              ? errorData.detail.map(e => `${e.loc?.join('.')}: ${e.msg}`).join(', ')
              : errorData.detail)
          : 'Failed to update pricing';
        throw new Error(errorMsg);
      }

      await response.json();
      setStep(3); // Move to step 3
    } catch (err) {
      setError(err.message);
      console.error('Step 2 error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Step 3: Finalize load with visibility & automation
  // Step 3: Just collect data, move to confirmation (Step 4)
  const handleStep3Next = () => {
    setStep(4); // No API call yet, just show confirmation
  };

  // Post load with status = ACTIVE (called from confirmation modal)
  const handlePostLoad = async () => {
    if (!loadId) {
      setError('Load ID not found. Please restart.');
      return;
    }
    
    setIsLoading(true);
    setError(null);
    
    try {
      const token = await getAuthToken();
      
      const visibilityMap = {
        'public': 'Public',
        'network': 'My Network Only',
        'private': 'Selected Carriers Only'
      };
      
      const response = await fetch(`${API_URL}/loads/${loadId}/step3?status=ACTIVE`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          visibility: visibilityMap[formData.visibility] || 'Public',
          selected_carriers: formData.selectedCarriers,
          auto_match_ai: formData.autoMatch,
          instant_booking: formData.instantBooking,
          auto_post_to_freightpower: formData.autoPostToFreightpower,
          auto_post_to_truckstop: formData.autoPostToTruckstop,
          auto_post_to_123loadboard: formData.autoPostTo123loadboard,
          notify_on_carrier_views: formData.notifyOnCarrierViews,
          notify_on_offer_received: formData.notifyOnOfferReceived,
          notify_on_load_covered: formData.notifyOnLoadCovered
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || 'Failed to post load');
      }

      const data = await response.json();
      setMatchedCarriers(data.matches || []);
      onClose(); // Close modal after posting
    } catch (err) {
      setError(err.message);
      console.error('Post load error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Save load as draft (called from confirmation modal)
  const handleSaveDraft = async () => {
    if (!loadId) {
      setError('Load ID not found. Please restart.');
      return;
    }
    
    setIsLoading(true);
    setError(null);
    
    try {
      const token = await getAuthToken();
      
      const visibilityMap = {
        'public': 'Public',
        'network': 'My Network Only',
        'private': 'Selected Carriers Only'
      };
      
      const response = await fetch(`${API_URL}/loads/${loadId}/step3?status=DRAFT`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          visibility: visibilityMap[formData.visibility] || 'Public',
          selected_carriers: formData.selectedCarriers,
          auto_match_ai: formData.autoMatch,
          instant_booking: formData.instantBooking,
          auto_post_to_freightpower: formData.autoPostToFreightpower,
          auto_post_to_truckstop: formData.autoPostToTruckstop,
          auto_post_to_123loadboard: formData.autoPostTo123loadboard,
          notify_on_carrier_views: formData.notifyOnCarrierViews,
          notify_on_offer_received: formData.notifyOnOfferReceived,
          notify_on_load_covered: formData.notifyOnLoadCovered
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || 'Failed to save draft');
      }

      onClose(); // Close modal after saving
    } catch (err) {
      setError(err.message);
      console.error('Save draft error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Generate AI driver instructions
  const handleGenerateInstructions = async () => {
    if (!loadId) return;
    
    setIsLoading(true);
    
    try {
      const token = await getAuthToken();
      
      const response = await fetch(`${API_URL}/loads/generate-instructions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          load_id: loadId,
          origin: formData.origin,
          destination: formData.destination,
          equipment_type: formData.equipmentType,
          commodity: formData.commodity,
          special_requirements: formData.specialRequirements
        })
      });

      if (!response.ok) {
        throw new Error('Failed to generate instructions');
      }

      const data = await response.json();
      setFormData(prev => ({
        ...prev,
        notes: data.instructions
      }));
    } catch (err) {
      console.error('Generate instructions error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleNext = () => {
    if (step === 1) {
      handleStep1Submit();
    } else if (step === 2) {
      handleStep2Submit();
    } else if (step === 3) {
      handleStep3Next(); // Just move to confirmation, don't post yet
    } else if (step < 4) {
      setStep(step + 1);
    }
  };

  const handleBack = () => {
    if (step > 1) setStep(step - 1);
  };

  const handleReviewLoad = () => {
    handleStep3Next(); // Just move to confirmation
  };

  const handleFinalPostLoad = () => {
    // Removed - using handlePostLoad now
  };

  return (
    <div className="add-loads-overlay" onClick={onClose}>
      <div className="add-loads-modal" onClick={(e) => e.stopPropagation()}>
        <button className="add-loads-close" aria-label="Close" onClick={onClose}>×</button>
        
        <div className="add-loads-page">
          <div className="add-loads-container">
            {/* STEP 1: Route & Equipment */}
            {step === 1 && (
              <div className="add-loads-step">
                <div className="step-header">
                  <h2>Create New Load</h2>
                  <p className="step-subtitle">Step 1 of 3 – Route & Equipment</p>
                  <p className="step-description">{loadId ? `Load ID: ${loadId}` : 'Load ID generated after Step 1'}</p>
                  {error && <div style={{color: 'red', marginTop: '10px'}}>{error}</div>}
                </div>

                <div className="form-section">
                  <h4 className="section-title">Route Information</h4>
                  <p className="section-desc">Where the shipment is picked up and delivered</p>
                  
                  <div className="grid-2">
                    <div className="form-group">
                      <label>Origin *</label>
                      <Geocoder
                        value={formData.origin}
                        onChange={(e) => handleInputChange({ target: { name: 'origin', value: e.target.value } })}
                        onSelect={(location) => {
                          setFormData(prev => ({ ...prev, origin: location.label }));
                        }}
                        placeholder="City, State, Zip or Facility"
                      />
                    </div>
                    <div className="form-group">
                      <label>Destination *</label>
                      <Geocoder
                        value={formData.destination}
                        onChange={(e) => handleInputChange({ target: { name: 'destination', value: e.target.value } })}
                        onSelect={(location) => {
                          setFormData(prev => ({ ...prev, destination: location.label }));
                        }}
                        placeholder="City, State, Zip or Facility"
                      />
                    </div>
                  </div>

                  {/* Route Preview Map */}
                  {formData.origin && formData.destination && (
                    <div className="form-group" style={{ marginTop: '20px' }}>
                      <label>Route Preview</label>
                      <div style={{ marginTop: '8px', border: '1px solid #e5e7eb', borderRadius: '8px', overflow: 'hidden' }}>
                        <RouteMap
                          origin={formData.origin}
                          destination={formData.destination}
                          waypoints={additionalRoutes.map(r => r.location)}
                          truckType={formData.equipmentType === 'Dry Van' ? 'dryVan' : 
                                     formData.equipmentType === 'Reefer' ? 'reefer' :
                                     formData.equipmentType === 'Flatbed' ? 'flatbed' : 'dryVan'}
                          onRouteCalculated={(data) => {
                            setRouteData(data);
                            setEstimatedDistance(data.distance_miles);
                            setEstimatedTransitTime(data.duration_hours);
                          }}
                          height="300px"
                        />
                      </div>
                    </div>
                  )}

                  <div className="grid-2" style={{ marginTop: '10px' }}>
                    <div className="form-group">
                      <label>Pickup Date *</label>
                      <input
                        type="date"
                        name="pickupDate"
                        value={formData.pickupDate}
                        onChange={handleInputChange}
                        min={new Date().toISOString().split('T')[0]}
                      />
                    </div>
                    <div className="form-group">
                      <label>Delivery Date</label>
                      <input
                        type="date"
                        name="deliveryDate"
                        value={formData.deliveryDate}
                        onChange={handleInputChange}
                        min={new Date().toISOString().split('T')[0]}
                      />
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">Equipment & Load Type</h4>
                  <p className="section-desc">Define how this load should be handled</p>
                  
                  <div className="grid-2">
                    <div className="form-group">
                      <label>Equipment Type *</label>
                      <select
                        name="equipmentType"
                        value={formData.equipmentType}
                        onChange={handleInputChange}
                      >
                        <option>Dry Van</option>
                        <option>Reefer</option>
                        <option>Flatbed</option>
                        <option>Stepdeck</option>
                        <option>Power Only</option>
                      </select>
                    </div>
                    <div className="form-group">
                      <label>Weight (lbs) *</label>
                      <input
                        type="text"
                        name="weight"
                        placeholder="e.g. 42,000"
                        value={formData.weight}
                        onChange={handleInputChange}
                      />
                    </div>
                  </div>

                  <div className="form-group" style={{ marginTop: '10px' }}>
                    <label>Load Type </label>
                    <div className="load-type-selector">
                      <button
                        className={`load-type-btn ${formData.loadType === 'FTL' ? 'active' : ''}`}
                        onClick={() => handleLoadTypeSelect('FTL')}
                      >
                        <div className="btn-icon">📦</div>
                        <div className="btn-label">FTL</div>
                        <div className="btn-desc">Dedicated trailer, no sharing</div>
                      </button>
                      <button
                        className={`load-type-btn ${formData.loadType === 'LTL' ? 'active' : ''}`}
                        onClick={() => handleLoadTypeSelect('LTL')}
                      >
                        <div className="btn-icon">📫</div>
                        <div className="btn-label">LTL</div>
                        <div className="btn-desc">Shared space, multiple shippers</div>
                      </button>
                    </div>
                  </div>

                  <div className="form-group" style={{ marginTop: '10px' }}>
                    <label>Pallet Count</label>
                    <input
                      type="text"
                      name="palletCount"
                      placeholder="Optional"
                      value={formData.palletCount}
                      onChange={handleInputChange}
                    />
                  </div>

                  <div className="info-box">
                    <p><strong>Estimated Distance:</strong> {estimatedDistance ? `${estimatedDistance.toFixed(1)} miles` : 'Calculating...'}</p>
                    <p><strong>Estimated Transit Time:</strong> {estimatedTransitTime ? `${estimatedTransitTime.toFixed(1)} hours (~${Math.ceil(estimatedTransitTime / 24)} days)` : 'Calculating...'}</p>
                  </div>
                </div>

                {/* Additional Routes Section */}
                <div className="add-route-box">
                  <button 
                    className="add-route-btn" 
                    type="button"
                    onClick={() => setShowAddRoute(!showAddRoute)}
                  >
                    + Add Additional Route & Equipment
                  </button>
                  <p className="add-route-desc">For multi-stop or complex shipments</p>
                  
                  {showAddRoute && (
                    <div className="additional-route-form" style={{
                      marginTop: '16px',
                      padding: '16px',
                      background: '#f8fafc',
                      borderRadius: '8px',
                      border: '1px solid #e2e8f0'
                    }}>
                      <div className="grid-3" style={{ marginBottom: '12px' }}>
                        <div className="form-group">
                          <label>Location</label>
                          <input
                            type="text"
                            placeholder="City, State or ZIP"
                            value={newRouteLocation}
                            onChange={(e) => setNewRouteLocation(e.target.value)}
                          />
                        </div>
                        <div className="form-group">
                          <label>Stop Type</label>
                          <select
                            value={newRouteType}
                            onChange={(e) => setNewRouteType(e.target.value)}
                          >
                            <option value="pickup">Pickup</option>
                            <option value="delivery">Delivery</option>
                            <option value="stopover">Stopover</option>
                          </select>
                        </div>
                        <div className="form-group">
                          <label>Date</label>
                          <input
                            type="date"
                            value={newRouteDate}
                            onChange={(e) => setNewRouteDate(e.target.value)}
                          />
                        </div>
                      </div>
                      <div style={{ display: 'flex', gap: '8px' }}>
                        <button 
                          className="btn small-cd" 
                          type="button"
                          onClick={handleAddRoute}
                          disabled={!newRouteLocation || !newRouteDate}
                        >
                          Add Stop
                        </button>
                        <button 
                          className="btn small ghost-cd" 
                          type="button"
                          onClick={() => setShowAddRoute(false)}
                        >
                          Cancel
                        </button>
                      </div>
                    </div>
                  )}
                  
                  {/* Display added routes */}
                  {additionalRoutes.length > 0 && (
                    <div className="added-routes" style={{
                      marginTop: '16px',
                      padding: '12px',
                      background: '#fff',
                      borderRadius: '8px',
                      border: '1px solid #e2e8f0'
                    }}>
                      <h5 style={{ marginBottom: '12px', fontSize: '14px', fontWeight: '600' }}>
                        Additional Stops ({additionalRoutes.length})
                      </h5>
                      {additionalRoutes.map((route, index) => (
                        <div
                          key={index}
                          style={{
                            display: 'flex',
                            justifyContent: 'space-between',
                            alignItems: 'center',
                            padding: '8px 12px',
                            marginBottom: '8px',
                            background: '#f8fafc',
                            borderRadius: '6px',
                            border: '1px solid #e2e8f0'
                          }}
                        >
                          <div>
                            <span style={{ fontWeight: '600', marginRight: '8px' }}>
                              {route.location}
                            </span>
                            <span style={{
                              padding: '2px 8px',
                              borderRadius: '4px',
                              fontSize: '12px',
                              marginRight: '8px',
                              background: route.type === 'pickup' ? '#dbeafe' : route.type === 'delivery' ? '#d1fae5' : '#fef3c7',
                              color: route.type === 'pickup' ? '#1e40af' : route.type === 'delivery' ? '#065f46' : '#92400e'
                            }}>
                              {route.type}
                            </span>
                            <span style={{ color: '#6b7280', fontSize: '14px' }}>
                              {route.date}
                            </span>
                          </div>
                          <button
                            type="button"
                            onClick={() => handleRemoveRoute(index)}
                            style={{
                              background: 'none',
                              border: 'none',
                              color: '#ef4444',
                              cursor: 'pointer',
                              fontSize: '18px'
                            }}
                          >
                            ×
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Multiple Pickups and Multiple Stop Options */}
                <div className="form-group" style={{ marginTop: '20px', display: 'flex', gap: '12px' }}>
                  <button
                    type="button"
                    className={`btn small-cd ${additionalRoutes.some(r => r.type === 'pickup') ? 'active' : ''}`}
                    onClick={() => {
                      if (!showAddRoute) {
                        setShowAddRoute(true)
                        setNewRouteType('pickup')
                      } else if (newRouteType !== 'pickup') {
                        setNewRouteType('pickup')
                      } else {
                        setShowAddRoute(false)
                      }
                    }}
                    style={{
                      flex: 1,
                      background: additionalRoutes.some(r => r.type === 'pickup') ? '#3b82f6' : '#f3f4f6',
                      color: additionalRoutes.some(r => r.type === 'pickup') ? 'white' : '#374151',
                      border: '1px solid #e5e7eb'
                    }}
                  >
                    <i className="fa-solid fa-truck-pickup" style={{ marginRight: '8px' }}></i>
                    Multiple Pickups
                  </button>
                  <button
                    type="button"
                    className={`btn small-cd ${additionalRoutes.some(r => r.type === 'delivery' || r.type === 'stopover') ? 'active' : ''}`}
                    onClick={() => {
                      if (!showAddRoute) {
                        setShowAddRoute(true)
                        setNewRouteType('delivery')
                      } else if (newRouteType !== 'delivery' && newRouteType !== 'stopover') {
                        setNewRouteType('delivery')
                      } else {
                        setShowAddRoute(false)
                      }
                    }}
                    style={{
                      flex: 1,
                      background: additionalRoutes.some(r => r.type === 'delivery' || r.type === 'stopover') ? '#3b82f6' : '#f3f4f6',
                      color: additionalRoutes.some(r => r.type === 'delivery' || r.type === 'stopover') ? 'white' : '#374151',
                      border: '1px solid #e5e7eb'
                    }}
                  >
                    <i className="fa-solid fa-route" style={{ marginRight: '8px' }}></i>
                    Multiple Stop
                  </button>
                </div>

                <div className="step-actions">
                  <button className="btn small ghost-cd" onClick={onClose}>Cancel</button>
                  <button 
                    className="btn small-cd" 
                    onClick={handleNext}
                    disabled={isLoading || !formData.origin || !formData.destination || !formData.pickupDate || !formData.weight}
                  >
                    {isLoading ? 'Creating...' : 'Next → Price & Details'}
                  </button>
                </div>
              </div>
            )}

            {/* STEP 2: Price & Details */}
            {step === 2 && (
              <div className="add-loads-step">
                <div className="step-header">
                  <h2>Create New Load</h2>
                  <p className="step-subtitle">Step 2 of 3 – Price & Details</p>
                  <p className="step-description">Load ID: {loadId || 'FP-2504-611-00123'}</p>
                </div>

                <div className="form-section">
                  <h4 className="section-title">Pricing Model</h4>
                  <p className="section-desc">How carriers will be compensated for this load</p>
                  
                  <div className="pricing-model-selector">
                    <button
                      className={`pricing-btn ${formData.rateType === 'flatRate' ? 'active' : ''}`}
                      onClick={() => setFormData(prev => ({ ...prev, rateType: 'flatRate' }))}
                    >
                      <div className="pricing-icon">💚</div>
                      <div className="pricing-label">Flat Rate</div>
                      <div className="pricing-desc">One total price for the load</div>
                    </button>
                    <button
                      className={`pricing-btn ${formData.rateType === 'perMile' ? 'active' : ''}`}
                      onClick={() => setFormData(prev => ({ ...prev, rateType: 'perMile' }))}
                    >
                      <div className="pricing-icon">📍</div>
                      <div className="pricing-label">Per Mile</div>
                      <div className="pricing-desc">Calculated from total distance</div>
                    </button>
                    <button
                      className={`pricing-btn ${formData.rateType === 'hourly' ? 'active' : ''}`}
                      onClick={() => setFormData(prev => ({ ...prev, rateType: 'hourly' }))}
                    >
                      <div className="pricing-icon">⏰</div>
                      <div className="pricing-label">Per CWT</div>
                      <div className="pricing-desc">Per hundred-weight pricing</div>
                    </button>
                  </div>
                </div>

                <div className="form-section">
                  {formData.rateType === 'perMile' && estimatedDistance && (
                    <div style={{
                      padding: '12px 16px',
                      background: '#f0f9ff',
                      border: '1px solid #3b82f6',
                      borderRadius: '8px',
                      marginBottom: '16px'
                    }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <div>
                          <strong style={{ color: '#1e40af' }}>Estimated Total:</strong>
                          <span style={{ marginLeft: '8px', color: '#6b7280' }}>
                            {estimatedDistance} miles × ${formData.linehaul || '0'}/mile
                          </span>
                        </div>
                        <div style={{ fontSize: '20px', fontWeight: '700', color: '#1e40af' }}>
                          ${formData.linehaul ? (estimatedDistance * parseFloat(formData.linehaul)).toFixed(2) : '0.00'}
                        </div>
                      </div>
                    </div>
                  )}
                  <div className="grid-2">
                    <div className="form-group">
                      <label>Linehaul Rate ($) *{formData.rateType === 'perMile' ? ' (per mile)' : ''}</label>
                      <input
                        type="text"
                        name="linehaul"
                        placeholder={formData.rateType === 'perMile' ? 'e.g. 2.50' : 'e.g. 2,750'}
                        value={formData.linehaul}
                        onChange={handleInputChange}
                      />
                    </div>
                    <div className="form-group">
                      <label>Fuel Surcharge ($)</label>
                      <input
                        type="text"
                        name="fuelSurcharge"
                        placeholder="Optional"
                        value={formData.fuelSurcharge}
                        onChange={handleInputChange}
                      />
                    </div>
                  </div>

                  <div className="form-section">
                    <h4 className="section-title" style={{marginTop: '20px'}}>Advanced Charges</h4>
                    <p className="section-desc">Additional charges beyond base rate (detention, layover, etc.)</p>
                    
                    <div className="advanced-pricing-form">
                      <div className="advanced-pricing-inputs">
                        <input
                          type="text"
                          placeholder="Charge Name (e.g. Detention, Layover)"
                          value={chargeName}
                          onChange={(e) => setChargeName(e.target.value)}
                          className="charge-name-input"
                          style={{flex: 1}}
                        />
                        <input
                          type="number"
                          placeholder="Amount ($)"
                          value={chargeAmount}
                          onChange={(e) => setChargeAmount(e.target.value)}
                          className="charge-amount-input"
                          style={{width: '150px'}}
                        />
                        <button 
                          className="btn small-cd add-charge-btn"
                          onClick={handleAddCharge}
                        >
                          Add
                        </button>
                      </div>

                      {advancedCharges.length > 0 && (
                        <div className="charges-list">
                          {advancedCharges.map((charge, index) => (
                            <div key={index} className="charge-item">
                              <div className="charge-info">
                                <span className="charge-item-name">{charge.name}</span>
                                <span className="charge-amount">${parseFloat(charge.amount).toFixed(2)}</span>
                              </div>
                              <button 
                                className="charge-remove-btn"
                                onClick={() => handleRemoveCharge(index)}
                                aria-label="Remove charge"
                              >
                                ×
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>

                  <div className="form-section" >
                    <h4 className="section-title" style={{marginTop: '20px'}}>Commodity & Special Requirements</h4>
                    <p className="section-desc">Add freight details and special handling needs</p>
                    
                    <div className="form-group">
                      <label>Commodity</label>
                      <input
                        type="text"
                        name="commodity"
                        placeholder="e.g. Electronics, Produce, Machinery"
                        value={formData.commodity}
                        onChange={handleInputChange}
                      />
                    </div>
                    
                    <div className="advanced-pricing-form">
                      <div className="advanced-pricing-inputs">
                        <input
                          type="text"
                          placeholder="Special requirement (e.g. Hazmat, Team Driver, TWIC)"
                          value={chargeName}
                          onChange={(e) => setChargeName(e.target.value)}
                          className="charge-name-input"
                          style={{flex: 1}}
                        />
                        <button 
                          className="btn small-cd add-charge-btn"
                          onClick={handleAddCharge}
                        >
                          Add
                        </button>
                      </div>

                      {formData.specialRequirements.length > 0 && (
                        <div className="charges-list">
                          {formData.specialRequirements.map((req, index) => (
                            <div key={index} className="charge-item">
                              <div className="charge-info">
                                <span className="charge-item-name">{req}</span>
                              </div>
                              <button 
                                className="charge-remove-btn"
                                onClick={() => handleRemoveCharge(req)}
                                aria-label="Remove requirement"
                              >
                                ×
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">Payment Terms</h4>
                  <p className="section-desc">When carriers get paid after delivery</p>
                  
                  <select
                    name="paymentTerms"
                    value={formData.paymentTerms}
                    onChange={handleInputChange}
                    style={{width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #e5e7eb'}}
                  >
                    <option value="Quick Pay">Quick Pay (1-2 days)</option>
                    <option value="15 Days">Net 15</option>
                    <option value="30 Days">Net 30</option>
                    <option value="Custom">Factoring Available</option>
                  </select>
                </div>

                <div className="form-section">
                  <h4 className="section-title">Driver Instructions</h4>
                  <p className="section-desc">Shown to the driver after booking</p>
                  <button 
                    className="btn small ghost-cd" 
                    onClick={handleGenerateInstructions}
                    disabled={isLoading}
                    style={{marginBottom: '10px'}}
                  >
                    ✨ {isLoading ? 'Generating...' : 'Generate with AI'}
                  </button>
                  
                  <textarea
                    name="notes"
                    placeholder="Gate codes, check-in process, dock rules, contact details, safety requirements..."
                    value={formData.notes}
                    onChange={handleInputChange}
                    className="driver-textarea"
                  />
                </div>

                <div className="estimated-total">
                  <p><strong>Estimated Total Pay: ${calculateTotalPay().toLocaleString()}</strong></p>
                </div>

                <div className="step-actions">
                  <button className="btn small ghost-cd" onClick={handleBack}>← Back</button>
                  <button 
                    className="btn small-cd" 
                    onClick={handleNext}
                    disabled={isLoading || !formData.linehaul}
                  >
                    {isLoading ? 'Saving...' : 'Next → Visibility'}
                  </button>
                </div>
              </div>
            )}

            {/* STEP 3: Visibility & Preferences */}
            {step === 3 && (
              <div className="add-loads-step">
                <div className="step-header">
                  <h2>Create New Load</h2>
                  <p className="step-subtitle">Step 3 of 3 – Visibility & Preferences</p>
                  <p className="step-description">Load ID: {loadId || 'FP-2504-611-00123'}</p>
                  {error && <div style={{color: 'red', marginTop: '10px'}}>{error}</div>}
                </div>

                <div className="form-section">
                  <h4 className="section-title">Load Visibility</h4>
                  <p className="section-desc">Choose who can see and book this load</p>
                  
                  <div className="visibility-selector">
                    <button
                      className={`visibility-btn ${formData.visibility === 'public' ? 'active' : ''}`}
                      onClick={() => handleVisibilitySelect('public')}
                    >
                      <div className="visibility-icon">🌐</div>
                      <div className="visibility-label">Public Marketplace</div>
                      <div className="visibility-desc">Visible to all approved carriers</div>
                    </button>
                    <button
                      className={`visibility-btn ${formData.visibility === 'network' ? 'active' : ''}`}
                      onClick={() => handleVisibilitySelect('network')}
                    >
                      <div className="visibility-icon">🤝</div>
                      <div className="visibility-label">My Network</div>
                      <div className="visibility-desc">Preferred and contracted carriers</div>
                    </button>
                    <button
                      className={`visibility-btn ${formData.visibility === 'private' ? 'active' : ''}`}
                      onClick={() => handleVisibilitySelect('private')}
                    >
                      <div className="visibility-icon">🔒</div>
                      <div className="visibility-label">Private</div>
                      <div className="visibility-desc">Invitation only, select carriers</div>
                    </button>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">Automation</h4>
                  <p className="section-desc">Speed up booking with intelligent automation.</p>
                  
                  <div className="automation-items">
                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Auto Match Carriers with AI</div>
                        <div className="automation-desc">Automatically suggest best fit carriers</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="autoMatch"
                          checked={formData.autoMatch}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Instant Booking</div>
                        <div className="automation-desc">Allow carriers to book without approval</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="instantBooking"
                          checked={formData.instantBooking}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Post to FreightPower Network</div>
                        <div className="automation-desc">Publish to FreightPower marketplace</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="autoPostToFreightpower"
                          checked={formData.autoPostToFreightpower}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Post to TruckStop</div>
                        <div className="automation-desc">Publish to TruckStop.com load board</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="autoPostToTruckstop"
                          checked={formData.autoPostToTruckstop}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Post to 123Loadboard</div>
                        <div className="automation-desc">Publish to 123Loadboard.com</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="autoPostTo123loadboard"
                          checked={formData.autoPostTo123loadboard}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">Notifications</h4>
                  <p className="section-desc">Get alerts about carrier activity</p>
                  
                  <div className="automation-items">
                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Notify on Carrier Views</div>
                        <div className="automation-desc">Alert when carriers view this load</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="notifyOnCarrierViews"
                          checked={formData.notifyOnCarrierViews}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Notify on Offer Received</div>
                        <div className="automation-desc">Alert when carriers send booking offers</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="notifyOnOfferReceived"
                          checked={formData.notifyOnOfferReceived}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>

                    <div className="automation-row">
                      <div className="automation-left">
                        <div className="automation-title">Notify on Load Covered</div>
                        <div className="automation-desc">Alert when load is successfully booked</div>
                      </div>
                      <label className="toggle-label">
                        <input
                          type="checkbox"
                          name="notifyOnLoadCovered"
                          checked={formData.notifyOnLoadCovered}
                          onChange={handleInputChange}
                          className="toggle-input"
                        />
                        <span className="toggle-slider"></span>
                      </label>
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h4 className="section-title">AI Recommendations</h4>
                  <p className="section-desc">Smart insights based on your load details</p>
                  
                  {matchedCarriers.length > 0 ? (
                    <div className="ai-recommendations">
                      <div className="ai-item">
                        <div className="ai-title">✅ Matched Carriers Found</div>
                        <div className="ai-desc">{matchedCarriers.length} carriers matched with scores</div>
                      </div>
                      {matchedCarriers.slice(0, 3).map((match, idx) => (
                        <div key={idx} className="ai-item">
                          <div className="ai-title">Carrier: {match.carrier_id}</div>
                          <div className="ai-desc">Score: {(match.score * 100).toFixed(0)}% - {match.reasons?.join(', ')}</div>
                          <div className="ai-icon">🚛</div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="ai-recommendations">
                      <div className="ai-item">
                        <div className="ai-title">Best Time to Post</div>
                        <div className="ai-desc">Wednesday 10:00 AM – Max carrier engagement</div>
                        <div className="ai-icon">🕐</div>
                      </div>

                      <div className="ai-item">
                        <div className="ai-title">Rate Analysis</div>
                        <div className="ai-desc">Current rate is competitive for this lane</div>
                        <div className="ai-icon">📊</div>
                      </div>

                      <div className="ai-item">
                        <div className="ai-title">Matching Ready</div>
                        <div className="ai-desc">AI will find best carriers when posted</div>
                        <div className="ai-icon">✅</div>
                      </div>
                    </div>
                  )}
                </div>

                <div className="review-summary">
                  <h4>Review Summary</h4>
                  <div className="summary-grid">
                    <div className="summary-item">
                      <div className="summary-label">Route</div>
                      <div className="summary-value">{formData.origin} → {formData.destination}</div>
                    </div>
                    <div className="summary-item">
                      <div className="summary-label">Equipment</div>
                      <div className="summary-value">{formData.equipmentType} - {formData.loadType}</div>
                    </div>
                    <div className="summary-item">
                      <div className="summary-label">Total Pay</div>
                      <div className="summary-value">${calculateTotalPay().toLocaleString()}</div>
                    </div>
                  </div>
                  <div className="summary-notes">
                    <p>✅ Everything looks good and ready to post</p>
                    <p className="optional-note">You can edit this load later if needed</p>
                  </div>
                </div>

                <div className="step-actions">
                  <button className="btn small ghost-cd" onClick={handleBack}>← Back</button>
                  <button 
                    className="btn small-cd" 
                    onClick={handleReviewLoad}
                    disabled={isLoading}
                  >
                    {isLoading ? 'Processing...' : 'Proceed to Post →'}
                  </button>
                </div>
              </div>
            )}

            {/* STEP 4: Review & Confirm */}
            {step === 4 && (
              <div className="add-loads-step">
                <div className="review-confirm-header">
                  <h2>Load Successfully Posted! 🎉</h2>
                  <p className="load-id-text">Load ID: {loadId}</p>
                </div>

                <div className="success-banner">
                  <svg className="success-icon" width="20" height="20" viewBox="0 0 20 20" fill="none">
                    <circle cx="10" cy="10" r="10" fill="#10b981"/>
                    <path d="M6 10l2 2 5-5" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  <span>Your load is now visible to carriers. {matchedCarriers.length > 0 ? `${matchedCarriers.length} carriers matched!` : ''}</span>
                </div>

                {matchedCarriers.length > 0 && (
                  <div className="confirm-card full-width" style={{marginBottom: '20px'}}>
                    <h3 className="confirm-card-title">🎯 AI Matched Carriers</h3>
                    <p className="confirm-card-subtitle">Top carriers for this load</p>
                    
                    <div className="ai-recommendations">
                      {matchedCarriers.map((match, idx) => (
                        <div key={idx} className="ai-item">
                          <div className="ai-title">#{idx + 1} - Carrier {match.carrier_id}</div>
                          <div className="ai-desc">
                            Match Score: {(match.score * 100).toFixed(0)}%
                            {match.reasons && ` • ${match.reasons.join(', ')}`}
                          </div>
                          <div className="ai-icon">🚛</div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <div className="confirmation-grid">
                  {/* Route Summary */}
                  <div className="confirm-card">
                    <h3 className="confirm-card-title">Route Summary</h3>
                    <p className="confirm-card-subtitle">Pickup & delivery details</p>
                    
                    <div className="confirm-detail-row">
                      <div className="confirm-detail-col">
                        <label className="confirm-label">Origin</label>
                        <p className="confirm-value">{formData.origin || '—'}</p>
                      </div>
                      <div className="confirm-detail-col">
                        <label className="confirm-label">Destination</label>
                        <p className="confirm-value">{formData.destination || '—'}</p>
                      </div>
                    </div>

                    <div className="confirm-detail-row">
                      <div className="confirm-detail-col">
                        <label className="confirm-label">Pickup Date</label>
                        <p className="confirm-value">{formData.pickupDate || '—'}</p>
                      </div>
                      <div className="confirm-detail-col">
                        <label className="confirm-label">Delivery Date</label>
                        <p className="confirm-value">{formData.deliveryDate || '—'}</p>
                      </div>
                    </div>

                    {estimatedDistance && (
                      <div className="confirm-detail-row">
                        <div className="confirm-detail-col">
                          <label className="confirm-label">Distance</label>
                          <p className="confirm-value">{estimatedDistance} miles</p>
                        </div>
                        {estimatedTransitTime && (
                          <div className="confirm-detail-col">
                            <label className="confirm-label">Transit Time</label>
                            <p className="confirm-value">{estimatedTransitTime} hours</p>
                          </div>
                        )}
                      </div>
                    )}
                  </div>

                  {/* Full Route Map */}
                  {formData.origin && formData.destination && (
                    <div className="confirm-detail-row" style={{ marginTop: '20px', gridColumn: '1 / -1' }}>
                      <div className="confirm-card" style={{ width: '100%' }}>
                        <h3 className="confirm-card-title">Route Map</h3>
                        <p className="confirm-card-subtitle">Full route visualization</p>
                        <div style={{ marginTop: '12px', border: '1px solid #e5e7eb', borderRadius: '8px', overflow: 'hidden' }}>
                          <RouteMap
                            origin={formData.origin}
                            destination={formData.destination}
                            waypoints={additionalRoutes.map(r => r.location)}
                            truckType={formData.equipmentType === 'Dry Van' ? 'dryVan' : 
                                       formData.equipmentType === 'Reefer' ? 'reefer' :
                                       formData.equipmentType === 'Flatbed' ? 'flatbed' : 'dryVan'}
                            height="400px"
                          />
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Pricing Summary */}
                  <div className="confirm-card">
                    <h3 className="confirm-card-title">Pricing Summary</h3>
                    <p className="confirm-card-subtitle">Carrier compensation</p>
                    
                    <div className="pricing-breakdown">
                      <div className="pricing-row">
                        <span>Linehaul</span>
                        <span className="pricing-amount">${formData.linehaul || '0'}</span>
                      </div>
                      {formData.fuelSurcharge && (
                        <div className="pricing-row">
                          <span>Fuel Surcharge</span>
                          <span className="pricing-amount">${formData.fuelSurcharge}</span>
                        </div>
                      )}
                      {advancedCharges.length > 0 && advancedCharges.map((charge, idx) => (
                        <div key={idx} className="pricing-row">
                          <span>{charge.name}</span>
                          <span className="pricing-amount">${parseFloat(charge.amount).toFixed(2)}</span>
                        </div>
                      ))}
                      <div className="pricing-divider"></div>
                      <div className="pricing-row pricing-total">
                        <span>Total Pay</span>
                        <span className="pricing-amount">${calculateTotalPay().toLocaleString()}</span>
                      </div>
                      <div className="pricing-row">
                        <span>Rate Type</span>
                        <span className="pricing-amount">{formData.rateType.replace('Rate', ' Rate')}</span>
                      </div>
                      <div className="pricing-row">
                        <span>Payment Terms</span>
                        <span className="pricing-amount">{formData.paymentTerms.replace('_', ' ')}</span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Equipment & Freight */}
                <div className="confirm-card full-width">
                  <h3 className="confirm-card-title">Equipment & Freight</h3>
                  <p className="confirm-card-subtitle">Load configuration</p>
                  
                  <div className="confirm-detail-row">
                    <div className="confirm-detail-col">
                      <label className="confirm-label">Equipment</label>
                      <p className="confirm-value">{formData.equipmentType} - {formData.loadType}</p>
                    </div>
                    <div className="confirm-detail-col">
                      <label className="confirm-label">Weight</label>
                      <p className="confirm-value">{formData.weight ? `${formData.weight} lbs` : '—'}</p>
                    </div>
                    {formData.palletCount && (
                      <div className="confirm-detail-col">
                        <label className="confirm-label">Pallets</label>
                        <p className="confirm-value">{formData.palletCount}</p>
                      </div>
                    )}
                  </div>

                  {formData.commodity && (
                    <div className="confirm-detail-row">
                      <div className="confirm-detail-col">
                        <label className="confirm-label">Commodity</label>
                        <p className="confirm-value">{formData.commodity}</p>
                      </div>
                    </div>
                  )}

                  {formData.specialRequirements.length > 0 && (
                    <div className="confirm-detail-row">
                      <div className="confirm-detail-col">
                        <label className="confirm-label">Special Requirements</label>
                        <div className="posting-tags">
                          {formData.specialRequirements.map((req, idx) => (
                            <span key={idx} className="posting-tag">{req}</span>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                {/* Posting & Booking */}
                <div className="confirm-card full-width" style={{marginTop: '20px'}}>
                  <h3 className="confirm-card-title">Posting & Automation</h3>
                  <p className="confirm-card-subtitle">Visibility & automation settings</p>
                  
                  <div className="posting-tags">
                    <span className="posting-tag">
                      {formData.visibility === 'public' ? '🌐 Public Marketplace' : 
                       formData.visibility === 'network' ? '🤝 My Network' : 
                       '🔒 Private'}
                    </span>
                    {formData.autoMatch && (
                      <span className="posting-tag">🤖 Auto-Match AI</span>
                    )}
                    {formData.instantBooking && (
                      <span className="posting-tag">⚡ Instant Booking</span>
                    )}
                    {formData.autoPostToFreightpower && (
                      <span className="posting-tag">✅ FreightPower</span>
                    )}
                    {formData.autoPostToTruckstop && (
                      <span className="posting-tag">✅ TruckStop</span>
                    )}
                    {formData.autoPostTo123loadboard && (
                      <span className="posting-tag">✅ 123Loadboard</span>
                    )}
                  </div>
                  
                  <div style={{marginTop: '15px'}}>
                    <p style={{fontSize: '14px', color: '#6b7280'}}>
                      📬 Notifications enabled for: 
                      {formData.notifyOnCarrierViews && ' Carrier Views'}
                      {formData.notifyOnOfferReceived && ' • Offers Received'}
                      {formData.notifyOnLoadCovered && ' • Load Covered'}
                    </p>
                  </div>
                </div>

                {/* Driver Instructions */}
                {formData.notes && (
                  <div className="confirm-card full-width" style={{marginTop: '20px'}}>
                    <h3 className="confirm-card-title">Driver Instructions</h3>
                    <p className="confirm-card-subtitle">Visible to carrier after booking</p>
                    
                    <p className="driver-instructions-text">
                      {formData.notes}
                    </p>
                  </div>
                )}

                <div className="confirm-actions">
                  {!isShipper && (
                    <button 
                      className="btn ghost-cd" 
                      onClick={handleSaveDraft}
                      disabled={isLoading}
                      style={{marginRight: '12px'}}
                    >
                      {isLoading ? 'Saving...' : '💾 Save Draft'}
                    </button>
                  )}
                  <button 
                    className="btn small-cd" 
                    onClick={handlePostLoad}
                    disabled={isLoading}
                  >
                    {isLoading ? 'Posting...' : '✓ Post Load'}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}