from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List


@dataclass(frozen=True)
class DocumentDefinition:
    code: str
    title: str
    description: str
    keywords: List[str]
    required_fields: List[str]
    optional_fields: List[str] = field(default_factory=list)
    validation_rules: List[str] = field(default_factory=list)
    expiry_alert_days: List[int] = field(default_factory=list)
    marketplace_fields: List[str] = field(default_factory=list)
    private_fields: List[str] = field(default_factory=list)
    prompt_guidance: str = ""


DOC_DEFINITIONS: Dict[str, DocumentDefinition] = {
    "CDL": DocumentDefinition(
        code="CDL",
        title="Commercial Driver License (Class A)",
        description="CDL photo ID verifying Class A driving privileges.",
        keywords=[
            "commercial driver license",
            "cdl",
            "class a",
            "driver license",
            "dmv",
        ],
        required_fields=[
            "driver_name",
            "date_of_birth",
            "address",
            "license_number",
            "issuing_state",
            "cdl_class",
            "endorsements",
            "restrictions",
            "issue_date",
            "expiry_date",
        ],
        optional_fields=["photo_id", "signature"],
        validation_rules=[
            "cdl_class must be 'A'",
            "expiry_date must be in the future",
            "alert at 60/30/7 days from expiry",
            "capture valid_license/about_to_expire/has_restrictions flags",
        ],
        expiry_alert_days=[60, 30, 7],
        marketplace_fields=["state", "cdl_class", "endorsements", "license_status", "restrictions_flag"],
        private_fields=["driver_name", "date_of_birth", "address", "license_number"],
        prompt_guidance="Extract all CDL fields verbatim; ensure CDL class is A and compute validity flags.",
    ),
    "MEDICAL": DocumentDefinition(
        code="MEDICAL",
        title="DOT Medical Certificate",
        description="Medical examiner's certificate proving driver qualification.",
        keywords=[
            "medical examiner",
            "391.41",
            "national registry",
            "fmcsr",
            "medical certificate",
        ],
        required_fields=[
            "driver_first_name",
            "driver_last_name",
            "license_number",
            "issuing_state",
            "driver_address",
            "cdl_clp_holder",
            "examiner_name",
            "examiner_phone",
            "examiner_type",
            "examiner_license",
            "examiner_state",
            "national_registry_number",
            "date_signed",
            "qualification_indicators",
            "expiry_date",
        ],
        optional_fields=["restrictions", "examiner_address"],
        validation_rules=[
            "expiry_date must be in the future",
            "driver name must match CDL",
            "national registry number must be 10 digits",
            "trigger expiry alerts at 60/30/7 days",
        ],
        expiry_alert_days=[60, 30, 7],
        marketplace_fields=["valid_medical_card", "expiry_date", "restrictions_flag", "state"],
        private_fields=["driver_address", "examiner_contact"],
        prompt_guidance="Capture driver + examiner info, checked restriction boxes, and the medical expiration date.",
    ),
    "DRIVER_REGISTRATION": DocumentDefinition(
        code="DRIVER_REGISTRATION",
        title="Driver Registration Application",
        description="Digital application capturing driver personal, residency, license, and experience history.",
        keywords=["driver application", "driver registration", "employment history", "auto-fill application"],
        required_fields=[
            "first_name",
            "middle_name",
            "last_name",
            "phone",
            "email",
            "date_of_birth",
            "current_address",
            "state_of_license",
            "cdl_number",
            "cdl_class",
            "endorsements",
            "cdl_expiry_date",
            "residency_history",
            "license_history",
            "driving_experience",
            "accident_history",
            "violation_history",
            "employment_history",
            "signature",
        ],
        optional_fields=["selfie_match", "manual_notes"],
        validation_rules=[
            "auto-fill fields from CDL/medical/MVR when available",
            "signature required",
        ],
        prompt_guidance="Summarize registration content for auto-fill; highlight sections needing manual input.",
    ),
    "CLEARINGHOUSE_CONSENT": DocumentDefinition(
        code="CLEARINGHOUSE_CONSENT",
        title="FMCSA Clearinghouse Consent Form",
        description="Driver consent authorizing Clearinghouse queries.",
        keywords=["clearinghouse", "consent", "dot drug", "query consent"],
        required_fields=["driver_name", "date", "company_name", "signature"],
        validation_rules=["auto-fill driver name/company/date; ensure signature present"],
        prompt_guidance="Confirm consent form is filled and signed; no additional validation.",
    ),
    "MVR": DocumentDefinition(
        code="MVR",
        title="Motor Vehicle Record",
        description="Official driving record covering status, accidents, violations, suspensions.",
        keywords=["motor vehicle record", "mvr", "state driver record", "driver history"],
        required_fields=[
            "driver_name",
            "date_of_birth",
            "license_number",
            "state",
            "license_status",
            "class",
            "endorsements",
            "restrictions",
            "issue_date",
            "expiry_date",
            "accidents",
            "violations",
            "suspensions",
        ],
        optional_fields=["medical_cert_status", "medical_cert_expiration"],
        validation_rules=[
            "flag clean_mvr / has_accidents / has_violations / has_serious_violations / has_suspension_revocation",
            "ensure CDL valid flag matches expiry/license status",
        ],
        prompt_guidance="List all accidents/violations for past 3-5 years and compute status flags.",
    ),
    "MVR_RELEASE": DocumentDefinition(
        code="MVR_RELEASE",
        title="Driver Release Consent (MVR Authorization)",
        description="Authorization form allowing carrier to pull MVR.",
        keywords=["mvr authorization", "driver release", "consent to obtain record"],
        required_fields=["driver_name", "date_of_birth", "license_number", "license_state", "company_name", "date", "signature"],
        optional_fields=["driver_email"],
        validation_rules=["ensure all identity fields present and signature captured"],
        prompt_guidance="Confirm release form is complete and signed; highlight missing identity details.",
    ),
    "COI_CARRIER": DocumentDefinition(
        code="COI_CARRIER",
        title="Carrier Certificate of Insurance",
        description="Carrier insurance certificate covering liability/cargo/physical damage.",
        keywords=["certificate of liability insurance", "acord", "cargo coverage", "liability insurance"],
        required_fields=[
            "insured_name",
            "insured_address",
            "producer",
            "insurance_companies",
            "policy_numbers",
            "coverage_types",
            "liability_limit",
            "cargo_limit",
            "physical_damage",
            "deductibles",
            "effective_date",
            "expiry_date",
            "vehicle_details",
        ],
        validation_rules=[
            "name/address must match carrier profile",
            "liability >= $1,000,000",
            "cargo >= $100,000",
            "policy must be active",
            "VINs must match fleet",
        ],
        expiry_alert_days=[60, 30, 7],
        prompt_guidance="Capture all coverage lines and verify minimum limits and active dates.",
    ),
    "MC_CERT": DocumentDefinition(
        code="MC_CERT",
        title="MC Authority Certificate (Carrier)",
        description="FMCSA authority letter for carriers.",
        keywords=["motor carrier certificate", "mc authority", "operating authority"],
        required_fields=[
            "carrier_name",
            "carrier_address",
            "mc_number",
            "usdot_number",
            "authority_type",
            "commerce_scope",
            "exclusions",
            "service_date",
            "status",
        ],
        validation_rules=[
            "MC and USDOT must match profile",
            "Authority type must be Motor Carrier of Property",
            "reject broker/passenger/household goods authority letters",
            "status must be active",
        ],
        prompt_guidance="Identify authority wording to distinguish carrier vs broker; confirm MC/USDOT.",
    ),
    "IFTA_LICENSE": DocumentDefinition(
        code="IFTA_LICENSE",
        title="IFTA License",
        description="International Fuel Tax Agreement license document.",
        keywords=["ifta license", "fuel tax agreement", "base jurisdiction"],
        required_fields=[
            "carrier_name",
            "address",
            "ifta_account_number",
            "license_year",
            "expiry_date",
            "base_jurisdiction",
        ],
        validation_rules=[
            "license year must be current",
            "name/address must match profile",
            "base jurisdiction should match carrier state",
        ],
        prompt_guidance="Extract license metadata and confirm current year + jurisdiction.",
    ),
    "IRP_IFTA_LETTER": DocumentDefinition(
        code="IRP_IFTA_LETTER",
        title="IRP / IFTA Registration Letter",
        description="Registration confirmation for IRP/IFTA accounts.",
        keywords=["irp registration", "apportioned plate letter", "ifta registration"],
        required_fields=[
            "carrier_name",
            "address",
            "issuing_state",
            "date_issued",
            "account_type",
            "account_status",
            "account_id",
        ],
        validation_rules=[
            "name/address must match profile",
            "document must come from state agency",
            "status must be active/approved",
            "reject retail receipts/titles/temp tags",
        ],
        prompt_guidance="Confirm it is an official IRP/IFTA letter and capture account identifiers.",
    ),
    "W9_CARRIER": DocumentDefinition(
        code="W9_CARRIER",
        title="Carrier W-9",
        description="Carrier tax form.",
        keywords=["form w-9", "request for taxpayer identification", "tin"],
        required_fields=["business_name", "dba", "federal_tax_classification", "address", "tin", "signature", "date"],
        validation_rules=[
            "TIN must be present and formatted XX-XXXXXXX",
            "Signature required",
            "Ensure legal name matches profile",
        ],
        prompt_guidance="Extract W-9 identity fields and confirm signature/date are present.",
    ),
    "UCR": DocumentDefinition(
        code="UCR",
        title="Unified Carrier Registration",
        description="UCR payment receipt/confirmation.",
        keywords=["unified carrier registration", "ucr", "payment confirmation"],
        required_fields=["legal_name", "usdot", "year", "payment_status", "receipt_number", "payment_date"],
        validation_rules=[
            "UCR year must be current",
            "USDOT matches profile",
            "payment status must be paid",
        ],
        prompt_guidance="Capture receipt info proving UCR was paid for current year.",
    ),
    "EIN_LETTER": DocumentDefinition(
        code="EIN_LETTER",
        title="IRS CP575 EIN Letter",
        description="IRS letter assigning EIN.",
        keywords=["cp575", "employer identification number", "irs"],
        required_fields=["legal_business_name", "ein", "business_address", "date", "responsible_party"],
        validation_rules=[
            "EIN matches profile",
            "Document must be CP575 (not W-9 or SS-4)",
        ],
        prompt_guidance="Extract EIN letter details and confirm authenticity.",
    ),
    "BOC3": DocumentDefinition(
        code="BOC3",
        title="BOC-3 Filing",
        description="FMCSA process agent designation.",
        keywords=["boc-3", "process agent", "designation of agents"],
        required_fields=["carrier_name", "mc_number", "usdot", "process_agent_company", "filing_date", "effective_date"],
        validation_rules=[
            "MC/USDOT must match profile",
            "Filing must be active and issued by real process agent",
        ],
        prompt_guidance="Ensure document is authentic BOC-3 listing process agents.",
    ),
    "CAB_CARD": DocumentDefinition(
        code="CAB_CARD",
        title="CAB Card (IRP Apportioned Plate)",
        description="Vehicle-specific apportioned plate documentation.",
        keywords=["cab card", "irp apportioned", "apportioned plate"],
        required_fields=[
            "carrier_name",
            "address",
            "usdot",
            "account_number",
            "fleet_number",
            "unit_number",
            "plate_number",
            "vin",
            "vehicle_make_model_year",
            "vehicle_type",
            "registered_weights",
            "axles",
            "irp_valid_dates",
            "jurisdictions",
        ],
        validation_rules=[
            "VIN and plate must match fleet records",
            "Document must correspond to truck tractor, not passenger vehicle",
            "Name/address must match carrier profile",
        ],
        prompt_guidance="Capture all vehicle identifiers and confirm it is an apportioned truck tractor.",
    ),
    "TRAILER_REG": DocumentDefinition(
        code="TRAILER_REG",
        title="Trailer Registration",
        description="State registration for trailers.",
        keywords=["trailer registration", "title and registration", "trailer plate"],
        required_fields=["plate", "vin", "year_make_type", "state", "expiration_date", "owner_name"],
        validation_rules=[
            "Trailer must belong to carrier",
            "Plate/VIN must match system records",
            "Registration must be active",
        ],
        prompt_guidance="Extract trailer identifiers and confirm registration status.",
    ),
    "VOIDED_CHECK_CARRIER": DocumentDefinition(
        code="VOIDED_CHECK_CARRIER",
        title="Carrier Voided Check",
        description="Banking proof for carrier payouts.",
        keywords=["voided check", "routing number", "account number"],
        required_fields=["routing_number", "account_number"],
        optional_fields=["account_holder_name", "bank_name"],
        validation_rules=[
            "Routing number must be valid format",
            "Reject if numbers unreadable or not a check",
        ],
        prompt_guidance="Read MICR line to capture routing/account numbers; note account holder if visible.",
    ),
    "CARRIER_BROKER_AGREEMENT": DocumentDefinition(
        code="CARRIER_BROKER_AGREEMENT",
        title="Carrier–Broker Agreement",
        description="Executed contract between carrier and FreightPower (or other broker).",
        keywords=["broker-carrier agreement", "transportation agreement", "contract"],
        required_fields=[
            "carrier_name",
            "carrier_address",
            "usdot",
            "mc_number",
            "broker_name",
            "broker_address",
            "agreement_date",
            "signatures",
        ],
        validation_rules=[
            "Agreement must be broker-carrier type",
            "USDOT/MC must match carrier profile",
            "Signatures required",
        ],
        prompt_guidance="Confirm agreement type and capture both parties + signatures.",
    ),
    "BROKER_AUTHORITY": DocumentDefinition(
        code="BROKER_AUTHORITY",
        title="Broker MC Authority Certificate",
        description="Operating authority proof for brokers.",
        keywords=["broker authority", "arranging transportation", "broker mc certificate"],
        required_fields=["broker_name", "address", "mc_number", "usdot", "service_date", "authority_type", "status"],
        validation_rules=[
            "Authority wording must indicate BROKER",
            "Reject documents mentioning transporting property/household goods",
            "MC/USDOT must match profile",
            "Authority status must be active",
        ],
        prompt_guidance="Look for 'as a broker' language; ensure authority type is correct.",
    ),
    "BROKER_COI": DocumentDefinition(
        code="BROKER_COI",
        title="Broker Certificate of Insurance",
        description="Insurance certificate for broker (general liability/contingent cargo).",
        keywords=["broker insurance", "contingent cargo", "general liability", "certificate of insurance"],
        required_fields=["broker_name", "address", "insurance_company", "policy_number", "coverage_type", "effective_date", "expiry_date"],
        validation_rules=[
            "Name must match broker profile",
            "Policy must be active",
            "Coverage must be appropriate for brokers (no auto liability/VINs)",
        ],
        prompt_guidance="Capture coverage lines relevant to brokers and ensure no vehicle-specific coverage.",
    ),
    "BROKER_W9": DocumentDefinition(
        code="BROKER_W9",
        title="Broker W-9",
        description="Broker tax form (same rules as carrier W-9).",
        keywords=["form w-9", "broker tin"],
        required_fields=["business_name", "dba", "federal_tax_classification", "address", "tin", "signature", "date"],
        validation_rules=[
            "TIN format validation",
            "Signature and date required",
            "Name must match broker profile",
        ],
        prompt_guidance="Extract W-9 details for broker entity.",
    ),
    "BMC_BOND": DocumentDefinition(
        code="BMC_BOND",
        title="BMC-84 / BMC-85 Bond",
        description="Broker surety/trust bond evidence.",
        keywords=["bmc-84", "bmc-85", "surety bond", "trust fund"],
        required_fields=["broker_name", "address", "mc_number", "usdot", "surety_company", "bond_amount", "effective_date"],
        validation_rules=[
            "Bond amount must equal $75,000",
            "Names and numbers must match broker profile",
            "Document must explicitly be BMC-84 or BMC-85",
        ],
        prompt_guidance="Confirm bond language and verify $75,000 amount.",
    ),
    "BROKER_BANKING": DocumentDefinition(
        code="BROKER_BANKING",
        title="Broker Voided Check",
        description="Banking proof for broker payouts.",
        keywords=["voided check", "broker bank"],
        required_fields=["routing_number", "account_number"],
        optional_fields=["account_holder_name", "bank_name"],
        validation_rules=[
            "Routing number format validation",
            "Reject if not a check or numbers unreadable",
        ],
        prompt_guidance="Same handling as carrier voided check.",
    ),
    "FMCSA_SYNC": DocumentDefinition(
        code="FMCSA_SYNC",
        title="FMCSA / SAFER Integration",
        description="Automated data pull of USDOT/MC safety, insurance, and authority data.",
        keywords=["fmcsa", "safer", "dot lookup"],
        required_fields=["usdot", "mc_number", "safety_rating", "insurance", "operating_authority", "compliance_history"],
        validation_rules=[
            "Use FMCSA data for automatic verification, fraud prevention, and doc matching",
        ],
        prompt_guidance="Background task (no PDF) that enriches carrier profile with FMCSA data.",
    ),
}
